// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoRentalOnlineShopApp.DataAccess;

#nullable disable

namespace VideoRentalOnlineShopApp.DataAccess.Migrations
{
    [DbContext(typeof(VideoRentalOnlineShopAppDbContext))]
    [Migration("20260719143404_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VideoRentalOnlineShopApp.Domain.Cast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Part")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Casts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MovieId = 1,
                            Name = "Leonardo DiCaprio",
                            Part = 0
                        },
                        new
                        {
                            Id = 2,
                            MovieId = 1,
                            Name = "Christopher Nolan",
                            Part = 1
                        },
                        new
                        {
                            Id = 3,
                            MovieId = 2,
                            Name = "Christian Bale",
                            Part = 0
                        },
                        new
                        {
                            Id = 4,
                            MovieId = 3,
                            Name = "Hayao Miyazaki",
                            Part = 1
                        },
                        new
                        {
                            Id = 5,
                            MovieId = 4,
                            Name = "Matthew McConaughey",
                            Part = 0
                        },
                        new
                        {
                            Id = 6,
                            MovieId = 5,
                            Name = "Keanu Reeves",
                            Part = 0
                        });
                });

            modelBuilder.Entity("VideoRentalOnlineShopApp.Domain.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgeRestriction")
                        .HasColumnType("int");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Length")
                        .HasColumnType("time");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeRestriction = 13,
                            Genre = 8,
                            IsAvailable = true,
                            Language = 0,
                            Length = new TimeSpan(0, 2, 28, 0, 0),
                            Quantity = 5,
                            ReleaseDate = new DateTime(2010, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 2,
                            AgeRestriction = 13,
                            Genre = 0,
                            IsAvailable = true,
                            Language = 0,
                            Length = new TimeSpan(0, 2, 32, 0, 0),
                            Quantity = 3,
                            ReleaseDate = new DateTime(2008, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 3,
                            AgeRestriction = 7,
                            Genre = 10,
                            IsAvailable = true,
                            Language = 7,
                            Length = new TimeSpan(0, 2, 5, 0, 0),
                            Quantity = 4,
                            ReleaseDate = new DateTime(2001, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Spirited Away"
                        },
                        new
                        {
                            Id = 4,
                            AgeRestriction = 13,
                            Genre = 8,
                            IsAvailable = true,
                            Language = 0,
                            Length = new TimeSpan(0, 2, 49, 0, 0),
                            Quantity = 6,
                            ReleaseDate = new DateTime(2014, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 5,
                            AgeRestriction = 16,
                            Genre = 8,
                            IsAvailable = true,
                            Language = 0,
                            Length = new TimeSpan(0, 2, 16, 0, 0),
                            Quantity = 2,
                            ReleaseDate = new DateTime(1999, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Matrix"
                        });
                });

            modelBuilder.Entity("VideoRentalOnlineShopApp.Domain.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RentedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Rentals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MovieId = 1,
                            RentedOn = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnedOn = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            MovieId = 2,
                            RentedOn = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnedOn = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("VideoRentalOnlineShopApp.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSubscriptionExpired")
                        .HasColumnType("bit");

                    b.Property<int>("SubscriptionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 25,
                            CardNumber = "1234567890123456",
                            CreatedOn = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "John Smith",
                            IsSubscriptionExpired = false,
                            SubscriptionType = 2
                        },
                        new
                        {
                            Id = 2,
                            Age = 31,
                            CardNumber = "9876543210987654",
                            CreatedOn = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Maria Johnson",
                            IsSubscriptionExpired = false,
                            SubscriptionType = 1
                        },
                        new
                        {
                            Id = 3,
                            Age = 18,
                            CardNumber = "5555666677778888",
                            CreatedOn = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Alex Brown",
                            IsSubscriptionExpired = true,
                            SubscriptionType = 0
                        });
                });

            modelBuilder.Entity("VideoRentalOnlineShopApp.Domain.Cast", b =>
                {
                    b.HasOne("VideoRentalOnlineShopApp.Domain.Movie", "Movie")
                        .WithMany("Casts")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("VideoRentalOnlineShopApp.Domain.Rental", b =>
                {
                    b.HasOne("VideoRentalOnlineShopApp.Domain.Movie", "Movie")
                        .WithMany("Rentals")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoRentalOnlineShopApp.Domain.User", "User")
                        .WithMany("Rentals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VideoRentalOnlineShopApp.Domain.Movie", b =>
                {
                    b.Navigation("Casts");

                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("VideoRentalOnlineShopApp.Domain.User", b =>
                {
                    b.Navigation("Rentals");
                });
#pragma warning restore 612, 618
        }
    }
}
